src/main/java/com/snowroad/web/ListController.java, src/main/java/com/snowroad/web/MainController.java, src/main/java/com/snowroad/web/dto/UserEventsListResponseDto.java
- 상세 리스트, 상세 컨텐츠(팝업/전시) 조회 관련 api 명세 작업
=> feat(상세 리스트) : api 명세서 목데이터 작업본

src/main/java/com/snowroad/search/map/domain/EventsGeoRepository.java, src/main/java/com/snowroad/search/map/dto/EventsGeoMapDto.java, src/main/java/com/snowroad/search/map/enums/GeoMapEnum.java, src/main/java/com/snowroad/search/map/interfaces/EventGeoMapQueryInterface.java, src/main/java/com/snowroad/search/map/service/EventGeoMapQueryService.java, src/main/java/com/snowroad/search/map/util/BoundingBoxCalculator.java, src/main/java/com/snowroad/search/map/util/Haversine.java, src/main/java/com/snowroad/search/map/web/EventGeoMapQueryController.java
- Bounding Box 를 이용한 데이터 필터링 이후 Haversine 공식으로 2Km 이내의 이벤트를 찾아내는 조회 처리
=> feat(Map 커스텀 마커 조회):  Map 데이터 조회 기능

src/main/java/com/snowroad/search/map/web/EventGeoMapQueryController.java
- fix(Map 커스텀 마커 조회): POST 조회로 변경
- fix(Map 커스텀 마커 조회): swagger 설명 변경
=> fix(Map 커스텀 마커 조회): POST 조회로 변경, swagger 설명 변경

src/main/java/com/snowroad/domain/marks/Mark.java, src/main/java/com/snowroad/domain/marks/MarkRepository.java, src/main/java/com/snowroad/service/MarkService.java, src/main/java/com/snowroad/web/MarkController.java, src/main/java/com/snowroad/web/dto/MarkResponseDTO.java, src/main/java/com/snowroad/web/dto/MarkSaveRequestDto.java, src/test/java/com/snowroad/domain/marks/MarkRepositoryTest.java
=> 즐겨찾기 api 명세 목데이터 추가

src/main/java/com/snowroad/event/domain/EventsRepository.java, src/main/java/com/snowroad/event/service/EventService.java, src/main/java/com/snowroad/event/web/EventController.java, src/main/java/com/snowroad/event/web/dto/DetailEventsResponseDto.java, src/main/java/com/snowroad/event/web/dto/HomeEventsResponseDto.java
- 메인화면 이벤트에 eventTypeCd 추가
- 기타 SQL 및 DetailEventsResponseDto 오류 수정
=> feat(이벤트) : 메인화면 이벤트 조회조건 추가 등

src/main/java/com/snowroad/event/domain/EventsRepository.java, src/main/java/com/snowroad/event/service/EventService.java, src/main/java/com/snowroad/event/web/EventController.java
=> feat(이벤트) : 메인화면 배너 조회 api 추가

src/main/java/com/snowroad/event/domain/EventsRepository.java, src/main/java/com/snowroad/event/service/EventService.java, src/main/java/com/snowroad/event/web/EventController.java, src/main/java/com/snowroad/event/web/dto/HomeEventsResponseDto.java
- 오픈/마감임박 D-DAY 추가
- 각 데이터 날짜형식 변경(YYYY=>YY)
- 팝업/전시 구분 코드 대문자 통일(all => ALL)
=> feat(메인이벤트) : 오픈임박 및 마감임박 데이터 D-DAY 추가 외 2건

src/main/java/com/snowroad/entity/View.java, src/main/java/com/snowroad/event/domain/EventsRepositoryCustom.java, src/main/java/com/snowroad/event/impl/EventsRepositoryImpl.java, src/main/java/com/snowroad/event/service/EventService.java, src/main/java/com/snowroad/event/web/EventController.java, src/main/java/com/snowroad/event/web/dto/DetailEventsResponseDto.java
- 리스트 조회관련 로직(controller,service,repo,impl) 추가
- view(조회수) 테이블 관련 엔티티 추가
=> feat(event) : 리스트 조회로직 추가 및 view 엔티티 생성

src/main/java/com/snowroad/event/domain/EventsRepositoryCustom.java, src/main/java/com/snowroad/event/impl/EventsRepositoryImpl.java, src/main/java/com/snowroad/event/service/EventService.java, src/main/java/com/snowroad/event/web/EventController.java
- 공통 기준에 맞게 페이지네이션 전달방식 수정
- 한 페이지당 보여주는 데이터 개수는 추후 프론트분들과 협의 후 수정
=>  feat(event) : 팝업/전시 리스트 페이지네이션 적용

src/main/java/com/snowroad/entity/Mark.java, src/main/java/com/snowroad/entity/MarkId.java, src/main/java/com/snowroad/event/web/EventController.java, src/main/java/com/snowroad/mark/domain/MarkRepository.java, src/main/java/com/snowroad/mark/impl/MarkRepositoryImpl.java, src/main/java/com/snowroad/mark/service/MarkService.java, src/main/java/com/snowroad/mark/web/MarkController.java, src/main/java/com/snowroad/mark/web/dto/MarkSaveRequestDto.java
- 팝업/전시 즐겨찾기 로직 추가
- event api 명세서 description 일부 변경 (eventTypeCd 관련)
- 미사용 api 삭제
=> feat(MARK/EVENT) : 팝업/전시 즐겨찾기 외 2건

src/main/java/com/snowroad/event/domain/EventsRepository.java, src/main/java/com/snowroad/event/domain/EventsRepositoryCustom.java, src/main/java/com/snowroad/event/impl/EventsRepositoryImpl.java, src/main/java/com/snowroad/event/service/EventService.java, src/main/java/com/snowroad/event/web/EventController.java, src/main/java/com/snowroad/event/web/dto/DetailEventsResponseDto.java, src/main/java/com/snowroad/mark/domain/MarkRepository.java, src/main/java/com/snowroad/mark/impl/MarkRepositoryImpl.java, src/main/java/com/snowroad/mark/service/MarkService.java, src/main/java/com/snowroad/mark/web/MarkController.java, src/main/java/com/snowroad/mark/web/dto/MarkSaveRequestDto.java
- 관심 팝업/전시 사용자id 파라미터 처리 변경(URL => 쿠키)
- 이벤트 리스트 일부 컬럼이 NULL로 출력되는 오류 해결
=> feat(MARK/EVENT) : 관심 팝업/전시 userId 파라미터 삭제 외 1건

src/main/java/com/snowroad/event/domain/EventsRepository.java, src/main/java/com/snowroad/event/impl/EventsRepositoryImpl.java
- user login 후 리스트 페이지 api 정상작동하지 않는 오류 수정
=> fix(EVENT) : 리스트페이지 오류 수정

src/main/java/com/snowroad/event/domain/EventsRepositoryCustom.java, src/main/java/com/snowroad/event/impl/EventsRepositoryImpl.java, src/main/java/com/snowroad/event/service/EventService.java, src/main/java/com/snowroad/event/web/EventController.java
-  queryDsl 변환
-  카테고리별 리스트 처리
=> fix(event-main) : 메인-추천 리스트

src/main/java/com/snowroad/mark/impl/MarkRepositoryImpl.java, src/main/java/com/snowroad/mark/web/MarkController.java
- 신규 insert시 userId를 제대로 받아오지 못하는 오류 수정
=> fix(mark-events) : 신규 즐겨찾기가 정상 작동하지 않는 오류 수정

src/main/java/com/snowroad/common/exception/EventNotFoundException.java, src/main/java/com/snowroad/common/exception/GlobalExceptionHandler.java, src/main/java/com/snowroad/entity/View.java, src/main/java/com/snowroad/event/impl/EventsRepositoryImpl.java, src/main/java/com/snowroad/event/web/EventController.java
- 상세 컨텐츠 내 조회수 표기 오류 수정
- view entity 수정
- 관련  exception 추가
=> fix(events-view) : 상세 컨텐츠 오류 수정 외 3건

src/main/java/com/snowroad/event/impl/EventsRepositoryImpl.java
- 리스트 조회 : sortType 40 (지역명 정렬) 누락 항목 추가
=> fix(events-sort) : 지역순 정렬조건 추가

src/main/java/com/snowroad/event/impl/EventsRepositoryImpl.java, src/main/java/com/snowroad/event/service/EventService.java, src/main/java/com/snowroad/userCategory/service/UserCategoryService.java
- 관심카테고리 등록수 최대 6개 변경
- 상세페이지 조회 exception 처리
=> fix(mark-categori 외 1) : 관심카테고리 등록수 변경 등

src/main/java/com/snowroad/event/domain/EventsRepository.java, src/main/java/com/snowroad/event/service/EventService.java
=> fix(event-main) : 메인 페이지 조회로직 수정

src/main/java/com/snowroad/event/impl/EventsRepositoryImpl.java, src/main/java/com/snowroad/event/web/dto/EventContentsResponseDto.java
- 리스트 페이지 팝업전시 조건 추가
- 상세페이지 이벤트 주소 url 추가
=> fix(리스트) : 리스트 / 상세페이지 조건수정

src/main/java/com/snowroad/MorphemeAnalyzer/annotation/MorphIndexing.java, src/main/java/com/snowroad/MorphemeAnalyzer/aspect/MorphIndexingAspect.java, src/main/java/com/snowroad/MorphemeAnalyzer/event/domain/EventNounMran.java, src/main/java/com/snowroad/event/service/EventService.java, src/main/java/com/snowroad/geodata/util/HaversineFormula.java, src/main/java/com/snowroad/search/repository/custom/SearchCustomRepositoryImpl.java
- fix(형태소분석기): 이벤트 저장시 형태소 분석처리 기능 추가
=> fix(형태소분석기): 이벤트 저장시 형태소 분석처리 기능 추가

src/main/java/com/snowroad/event/impl/EventsRepositoryImpl.java, src/main/java/com/snowroad/event/web/dto/EventContentsResponseDto.java
=> fix(상세페이지) : 이벤트 사진파일 dto 컬럼명 추가수정

src/main/java/com/snowroad/event/domain/EventsRepository.java, src/main/java/com/snowroad/event/service/EventService.java, src/main/java/com/snowroad/event/web/dto/HomeEventsResponseDto.java
=> fix(이벤트_배너) : 주소 컬럼 추가

src/main/java/com/snowroad/search/repository/custom/SearchCustomRepositoryImpl.java
fix(검색): 날짜가 없는 경우 마감된 데이터만 보이도록 설정함
=> fix(검색): 날짜가 없는 경우 마감된 데이터만 보이도록 설정함
